version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(message)s'
handlers:
  file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: logs/logfile.log
  console_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
loggers:
  main_logger:
    level: INFO
    handlers: [file_handler, console_handler]
    propagate: no
root:
  level: INFO
  handlers: [file_handler, console_handler]
